version: '3.2'
services:
  web:
    build: .
    ports:
      - '3000:3000'
    command: mix phx.server
    environment:
      - MIX_ENV=dev
      - PORT=3000
    volumes:
      - .:/app
    depends_on:
      - db
    tty: true
    stdin_open: true

  db:
    image: postgres
    ports:
      - '5432:5432'
    environment:
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=root
      - POSTGRES_HOST=db
    restart: always
    volumes:
      - postgres:/var/lib/postgresql/data
volumes:
  postgres:
